extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_pr128_21_ci4[];
extern u8 castle_grounds_dl_pr128_21_pal_rgba16[];
extern u8 castle_grounds_dl_shcity256_3_ci4[];
extern u8 castle_grounds_dl_shcity256_3_pal_rgba16[];
extern u8 castle_grounds_dl_Material_ia16[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[7];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_1[22];
extern Vtx castle_grounds_dl_Untitled_001_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Untitled_001_mesh_layer_5_vtx_0[50];
extern Vtx castle_grounds_dl_Untitled_002_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Untitled_002_mesh_layer_5_vtx_0[49];
extern Vtx castle_grounds_dl_Untitled_003_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Untitled_003_mesh_layer_5_vtx_0[50];
extern Vtx castle_grounds_dl_Untitled_005_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Untitled_005_mesh_layer_5_vtx_0[50];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_Untitled_001_mesh_layer_5[];
extern Gfx castle_grounds_dl_Untitled_002_mesh_layer_5[];
extern Gfx castle_grounds_dl_Untitled_003_mesh_layer_5[];
extern Gfx castle_grounds_dl_Untitled_005_mesh_layer_5[];
