#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/example/header.h"

const GeoLayout mario_stub_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_PLAYER, 0xB4, 100),
   GEO_OPEN_NODE(),
		GEO_ASM(0, geo_mirror_mario_backface_culling),
		// GEO_ASM(0, geo_mirror_mario_set_alpha),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, p1_object_0049F6B0_mesh_layer_1),
		GEO_ASM(1, geo_mirror_mario_backface_culling),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

#include "levels/example/geo.inc.c"
#include "levels/example/p1/geo.inc.c"
#include "levels/example/p2/geo.inc.c"
#include "levels/example/p3/geo.inc.c"
#include "levels/example/p4/geo.inc.c"
#include "levels/example/p5/geo.inc.c"
#include "levels/example/p6/geo.inc.c"
#include "levels/example/p7/geo.inc.c"
#include "levels/example/p8/geo.inc.c"
#include "levels/example/p9/geo.inc.c"
#include "levels/example/p10/geo.inc.c"
#include "levels/example/p11/geo.inc.c"
#include "levels/example/p12/geo.inc.c"
#include "levels/example/p13/geo.inc.c"
#include "levels/example/p14/geo.inc.c"
#include "levels/example/p15/geo.inc.c"
#include "levels/example/p16/geo.inc.c"
#include "levels/example/p17/geo.inc.c"
#include "levels/example/p18/geo.inc.c"
#include "levels/example/p19/geo.inc.c"
#include "levels/example/p20/geo.inc.c"
#include "levels/example/p21/geo.inc.c"
#include "levels/example/p22/geo.inc.c"
#include "levels/example/p23/geo.inc.c"
#include "levels/example/p24/geo.inc.c"
#include "levels/example/p28/geo.inc.c"
#include "levels/example/p29/geo.inc.c"
#include "levels/example/p30/geo.inc.c"
#include "levels/example/p31/geo.inc.c"
#include "levels/example/p32/geo.inc.c"
#include "levels/example/p33/geo.inc.c"
#include "levels/example/p34/geo.inc.c"
#include "levels/example/p35/geo.inc.c"
#include "levels/example/p36/geo.inc.c"
#include "levels/example/p37/geo.inc.c"
#include "levels/example/p38/geo.inc.c"
#include "levels/example/p39/geo.inc.c"
#include "levels/example/p40/geo.inc.c"
#include "levels/example/p41/geo.inc.c"
#include "levels/example/p42/geo.inc.c"
#include "levels/example/p43/geo.inc.c"
#include "levels/example/p44/geo.inc.c"
#include "levels/example/p45/geo.inc.c"
#include "levels/example/p46/geo.inc.c"
#include "levels/example/p47/geo.inc.c"
#include "levels/example/p48/geo.inc.c"
#include "levels/example/p49/geo.inc.c"
#include "levels/example/p50/geo.inc.c"
#include "levels/example/p51/geo.inc.c"
#include "levels/example/p52/geo.inc.c"
#include "levels/example/p53/geo.inc.c"
#include "levels/example/p54/geo.inc.c"
#include "levels/example/p55/geo.inc.c"
#include "levels/example/p56/geo.inc.c"
#include "levels/example/p57/geo.inc.c"
#include "levels/example/p58/geo.inc.c"
#include "levels/example/p59/geo.inc.c"
#include "levels/example/p60/geo.inc.c"
#include "levels/example/p61/geo.inc.c"
#include "levels/example/p62/geo.inc.c"
#include "levels/example/p63/geo.inc.c"
#include "levels/example/p64/geo.inc.c"
#include "levels/example/p65/geo.inc.c"
#include "levels/example/p66/geo.inc.c"
#include "levels/example/p67/geo.inc.c"
#include "levels/example/p68/geo.inc.c"
#include "levels/example/p69/geo.inc.c"
#include "levels/example/p70/geo.inc.c"
#include "levels/example/p71/geo.inc.c"
#include "levels/example/p72/geo.inc.c"
#include "levels/example/p73/geo.inc.c"
#include "levels/example/p74/geo.inc.c"
#include "levels/example/p75/geo.inc.c"
#include "levels/example/p76/geo.inc.c"
#include "levels/example/p77/geo.inc.c"
#include "levels/example/p78/geo.inc.c"
#include "levels/example/p79/geo.inc.c"
#include "levels/example/p80/geo.inc.c"
#include "levels/example/p81/geo.inc.c"
#include "levels/example/p82/geo.inc.c"
#include "levels/example/p83/geo.inc.c"
#include "levels/example/p84/geo.inc.c"