extern const GeoLayout example_area_1_geo[];
extern const GeoLayout example_area_1[];
extern const Collision example_area_1_collision[];
extern const MacroObject example_area_1_macro_objs[];
extern Vtx example_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx example_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx example_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_example_dl_f3dlite_material[];
extern Gfx mat_revert_example_dl_f3dlite_material[];
extern Gfx example_dl_Plane_mesh_layer_1[];
